### ISSUE TITLE
Secure boot shell?

### ISSUE THREAD

**Issue by bitRAKE** [pbatard/UEFI-Shell#1]
How do these EFI shell images work if secure boot shell is not possible?

https://github.com/bitRAKE/UEFI_playground/tree/master/firmware/OVMF_amd64
They are from here:
https://www.kraxel.org/repos/

My understanding is that the image just need to be signed and the key added to the whitelist. This is useful if one wants to use external media, but restrict it to known media and drivers/tools. Microsoft has said they will not sign EFI images, but doesn't this just effect MS devices without access to the whitelist?

I haven't tried these on real hardware. So, I am not completely certain.

Thank you for wonderful work with UEFI. It's a nice way to play with the bare metal.

**Comment by pbatard** [comment]
> How do these EFI shell images work if secure boot shell is not possible?

You just disable Secure Boot, as advised.

> https://github.com/bitRAKE/UEFI_playground/tree/master/firmware/OVMF_amd64

Anybody can build an OVMF firmware and add their public key to it, which then allows them to sign whatever EFI executable they please for Secure Boot (just like Microsoft does).

However what they signed will only work for that specific firmware. If you want to boot real hardware where SB enabled, then you have  no choice but have Microsoft or one of the holders of the other keys (like motherboard manufacturer, but then that won't work for other motherboards) to sign your EFI executable.

> My understanding is that the image just need to be signed and the key added to the whitelist.

And you can't add a public key to the whitelist unless it first gets signed using one of the private keys mentioned above, which, on __real__ hardware, you don't have access to (unless you first disable SB to replace them with your __own__ keys, but then you are back to the issue that what you signed will only ever boot on your specific machine, and not on someone else's, since they wouldn't have the same private keys as the ones you used).

And yeah, there's the semi special case of MokManager, but that still forces users to __manually__ go through MOK database enrollment (as well as create a __MAJOR__ security risk if you just tell users that they should just enroll your key because _"trust me, I'm not evil!!"_).

I simply do not know of any solution (well I kinda do, but it only works because someone did a bad job and it's been revoked by Microsoft in any up to date UEFI firmware) that can allow a real consumer PC that has Secure Boot enabled to boot a UEFI Shell for external UEFI media.

But, unless you are using one of the ill-fated ARM tablets (**not** ARM64) running Windows RT that Microsoft failed to push on consumers ~10 years ago (and that failed in part because Microsoft tried to take control away from users and was faced with a direct backlash from this action), Secure Boot can __always__ be disabled, so it's not really an issue.

If you want to boot into a UEFI Shell, you just have to disable Secure Boot.

**Comment by bitRAKE** [comment]
Thanks for the clarification. I didn't know of that two step process to sign images. Secure boot seems useless to me now.
