### ISSUE TITLE
Release bare shell{aa64,arm,ia32,riscv64,x64}.efi files

### ISSUE THREAD

**Issue by kc2zgu** [pbatard/UEFI-Shell#5]
The ISO image is useful for making bootable media on a dedicated device, but I expect many people will also want to add a shell executable to an existing system with its own EFI partition. The extra step of extracting the files from the iso image isn't too difficult, but since they need to be renamed to "shell" instead of "boot" this makes it a little more cumbersome when you don't want to clobber an existing default bootloader.

It would be nice to have the shell files available individually in the releases with the "shell" filenames.

**Comment by pbatard** [comment]
I'll see what I can do for the next release.

**Comment by FoxieFlakey** [comment]
this would be nice too for some people who just want the .efi file precisely and dont want to deal with mounting/extracting from ISO

**Comment by pbatard** [comment]
And now you guys **see** how much one has to fight to get this bloody thing going, because when it's not the EDK2 being broken [for no good reason](https://edk2.groups.io/g/devel/message/119117), then it's GitHub Actions. In the software world, even if you don't change anything, don't ever count on something that worked fine 6 months ago to work fine today...

**Comment by pbatard** [comment]
Finally!...

Individual Shells should now be available from the [latest release](https://github.com/pbatard/UEFI-Shell/releases).

And yes, I anticipate that the next thing people will want are the SHA-256 of these shells on the release page itself and not just [as part of the build log](https://github.com/pbatard/UEFI-Shell/actions/runs/9293562444/job/25576978957), but you'll have to wait for the 24H2 release before I look into that.
