### ISSUE TITLE
Does the Shell support reading some characteristics of the computer to determine whether instructions need to be run?

### ISSUE THREAD

**Issue by cbbos** [pbatard/UEFI-Shell#7]
For example, model/serial number, it seems that many versions do not support the judgment command.

**Comment by pbatard** [comment]
The Shell does not read model/serial number.

The `judgment` command is not part of the official UEFI Shell package (https://github.com/tianocore/edk2/tree/master/ShellPkg), and this project provides the official UEFI Shell, and not some version that may have been customized by a specific manufacturer to add more commands (in which case you will have to explain where you have seen that `judgment` command and what it does).

Since I believe I have answered your question, I will close this issue.
